version: 2.0

jobs:
  jdk8:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run: mvn verify

  jdk11:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - checkout
      - run: mvn verify

workflows:
  version: 2

  build-then-test:
    jobs:
      - jdk8
      - jdk11